[package]
name = "syntinct"
version = "0.1.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2021"

[dependencies]
enum-iterator = "1.4.1"
palette = "0.7.3"
serde = { version = "1.0.194", features = ["derive"] }
thiserror = "1.0.56"
