#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, enum_iterator::Sequence)]
#[non_exhaustive]
pub enum Category {
    ActiveSearchMatch,
    ActiveTab,
    ActiveTabBackground,
    BadSpelling,
    ColumnGuide,
    CursorLine,
    CursorLineNumber,
    DiffAdd,
    DiffChange,
    DiffDelete,
    DiffText,
    Folded,
    InactiveTab,
    InactiveTabBackground,
    LineNumber,
    MatchedBracket,
    MessageSeparator,
    ModeMessage,
    NonText,
    Normal,
    NormalBackground,
    Question,
    Search,
    SearchMatch,
    Selection,
    Special,
    StatusLine,
    TermCursor,
    UnfocusedTermCursor,
    Whitespace,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, enum_iterator::Sequence)]
#[non_exhaustive]
pub enum Token {
    Attribute,
    Boolean,
    Character,
    Comment,
    Constant,
    ConstGenericParameter,
    Delimiter,
    DocComment,
    Enum,
    Field,
    Float,
    Function,
    Identifier,
    Integer,
    Interface,
    Keyword,
    Link,
    Macro,
    Module,
    Operator,
    Parameter,
    String,
    Struct,
    Tag,
    Todo,
    Type,
    TypeParameter,
    Variable,
    Variant,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, enum_iterator::Sequence)]
pub enum DiagnosticLevel {
    Error,
    Warning,
    Info,
    Hint,
}
